var searchData=
[
  ['ibiosmanager',['IBiosManager',['../interface_snowflake_1_1_emulator_1_1_i_bios_manager.html',1,'Snowflake::Emulator']]],
  ['ibooleanmapping',['IBooleanMapping',['../interface_snowflake_1_1_configuration_1_1_i_boolean_mapping.html',1,'Snowflake::Configuration']]],
  ['iconfigurationcollection',['IConfigurationCollection',['../interface_snowflake_1_1_configuration_1_1_i_configuration_collection.html',1,'Snowflake::Configuration']]],
  ['iconfigurationcollection_3c_20t_20_3e',['IConfigurationCollection&lt; T &gt;',['../interface_snowflake_1_1_configuration_1_1_i_configuration_collection.html',1,'Snowflake::Configuration']]],
  ['iconfigurationcollectiondescriptor',['IConfigurationCollectionDescriptor',['../interface_snowflake_1_1_configuration_1_1_i_configuration_collection_descriptor.html',1,'Snowflake::Configuration']]],
  ['iconfigurationcollectionstore',['IConfigurationCollectionStore',['../interface_snowflake_1_1_configuration_1_1_i_configuration_collection_store.html',1,'Snowflake::Configuration']]],
  ['iconfigurationfile',['IConfigurationFile',['../interface_snowflake_1_1_configuration_1_1_i_configuration_file.html',1,'Snowflake::Configuration']]],
  ['iconfigurationoption',['IConfigurationOption',['../interface_snowflake_1_1_configuration_1_1_i_configuration_option.html',1,'Snowflake::Configuration']]],
  ['iconfigurationproperty',['IConfigurationProperty',['../interface_snowflake_1_1_configuration_1_1_i_configuration_property.html',1,'Snowflake::Configuration']]],
  ['iconfigurationsection',['IConfigurationSection',['../interface_snowflake_1_1_configuration_1_1_i_configuration_section.html',1,'Snowflake::Configuration']]],
  ['iconfigurationsection_3c_20t_20_3e',['IConfigurationSection&lt; T &gt;',['../interface_snowflake_1_1_configuration_1_1_i_configuration_section.html',1,'Snowflake::Configuration']]],
  ['iconfigurationsectiondescriptor',['IConfigurationSectionDescriptor',['../interface_snowflake_1_1_configuration_1_1_i_configuration_section_descriptor.html',1,'Snowflake::Configuration']]],
  ['iconfigurationserializer',['IConfigurationSerializer',['../interface_snowflake_1_1_configuration_1_1_i_configuration_serializer.html',1,'Snowflake::Configuration']]],
  ['iconfigurationtypemapper',['IConfigurationTypeMapper',['../interface_snowflake_1_1_configuration_1_1_i_configuration_type_mapper.html',1,'Snowflake::Configuration']]],
  ['iconfigurationvalue',['IConfigurationValue',['../interface_snowflake_1_1_configuration_1_1_i_configuration_value.html',1,'Snowflake::Configuration']]],
  ['icontrollerelementcollection',['IControllerElementCollection',['../interface_snowflake_1_1_input_1_1_controller_1_1_i_controller_element_collection.html',1,'Snowflake::Input::Controller']]],
  ['icontrollerelementinfo',['IControllerElementInfo',['../interface_snowflake_1_1_input_1_1_controller_1_1_i_controller_element_info.html',1,'Snowflake::Input::Controller']]],
  ['icontrollerlayout',['IControllerLayout',['../interface_snowflake_1_1_input_1_1_controller_1_1_i_controller_layout.html',1,'Snowflake::Input::Controller']]],
  ['icoreservice',['ICoreService',['../interface_snowflake_1_1_services_1_1_i_core_service.html',1,'Snowflake::Services']]],
  ['iemulatedport',['IEmulatedPort',['../interface_snowflake_1_1_emulator_1_1_i_emulated_port.html',1,'Snowflake::Emulator']]],
  ['iemulatoradapter',['IEmulatorAdapter',['../interface_snowflake_1_1_emulator_1_1_i_emulator_adapter.html',1,'Snowflake::Emulator']]],
  ['iemulatorinstance',['IEmulatorInstance',['../interface_snowflake_1_1_emulator_1_1_i_emulator_instance.html',1,'Snowflake::Emulator']]],
  ['ifilelibrary',['IFileLibrary',['../interface_snowflake_1_1_records_1_1_file_1_1_i_file_library.html',1,'Snowflake::Records::File']]],
  ['ifilerecord',['IFileRecord',['../interface_snowflake_1_1_records_1_1_file_1_1_i_file_record.html',1,'Snowflake::Records::File']]],
  ['ifilesignature',['IFileSignature',['../interface_snowflake_1_1_romfile_1_1_i_file_signature.html',1,'Snowflake::Romfile']]],
  ['ifilesignaturematcher',['IFileSignatureMatcher',['../interface_snowflake_1_1_romfile_1_1_i_file_signature_matcher.html',1,'Snowflake::Romfile']]],
  ['igamelibrary',['IGameLibrary',['../interface_snowflake_1_1_records_1_1_game_1_1_i_game_library.html',1,'Snowflake::Records::Game']]],
  ['igamerecord',['IGameRecord',['../interface_snowflake_1_1_records_1_1_game_1_1_i_game_record.html',1,'Snowflake::Records::Game']]],
  ['iinputdevice',['IInputDevice',['../interface_snowflake_1_1_input_1_1_device_1_1_i_input_device.html',1,'Snowflake::Input::Device']]],
  ['iinputenumerator',['IInputEnumerator',['../interface_snowflake_1_1_input_1_1_device_1_1_i_input_enumerator.html',1,'Snowflake::Input::Device']]],
  ['iinputmanager',['IInputManager',['../interface_snowflake_1_1_input_1_1_device_1_1_i_input_manager.html',1,'Snowflake::Input::Device']]],
  ['iinputmapping',['IInputMapping',['../interface_snowflake_1_1_configuration_1_1_input_1_1_i_input_mapping.html',1,'Snowflake::Configuration::Input']]],
  ['iinputoption',['IInputOption',['../interface_snowflake_1_1_configuration_1_1_input_1_1_i_input_option.html',1,'Snowflake::Configuration::Input']]],
  ['iinputserializer',['IInputSerializer',['../interface_snowflake_1_1_configuration_1_1_input_1_1_i_input_serializer.html',1,'Snowflake::Configuration::Input']]],
  ['iinputtemplate',['IInputTemplate',['../interface_snowflake_1_1_configuration_1_1_input_1_1_i_input_template.html',1,'Snowflake::Configuration::Input']]],
  ['iinputtemplate_3c_20t_20_3e',['IInputTemplate&lt; T &gt;',['../interface_snowflake_1_1_configuration_1_1_input_1_1_i_input_template.html',1,'Snowflake::Configuration::Input']]],
  ['ikeyedimagecache',['IKeyedImageCache',['../interface_snowflake_1_1_caching_1_1_i_keyed_image_cache.html',1,'Snowflake::Caching']]],
  ['ilibrary',['ILibrary',['../interface_snowflake_1_1_records_1_1_i_library.html',1,'Snowflake::Records']]],
  ['ilibrary_3c_20irecordmetadata_20_3e',['ILibrary&lt; IRecordMetadata &gt;',['../interface_snowflake_1_1_records_1_1_i_library.html',1,'Snowflake::Records']]],
  ['ilowlevelinputdevice',['ILowLevelInputDevice',['../interface_snowflake_1_1_input_1_1_device_1_1_i_low_level_input_device.html',1,'Snowflake::Input::Device']]],
  ['imappedcontrollerelement',['IMappedControllerElement',['../interface_snowflake_1_1_input_1_1_controller_1_1_mapped_1_1_i_mapped_controller_element.html',1,'Snowflake::Input::Controller::Mapped']]],
  ['imappedcontrollerelementcollection',['IMappedControllerElementCollection',['../interface_snowflake_1_1_input_1_1_controller_1_1_mapped_1_1_i_mapped_controller_element_collection.html',1,'Snowflake::Input::Controller::Mapped']]],
  ['imappedcontrollerelementcollectionstore',['IMappedControllerElementCollectionStore',['../interface_snowflake_1_1_input_1_1_i_mapped_controller_element_collection_store.html',1,'Snowflake::Input']]],
  ['imetadatable',['IMetadatable',['../interface_snowflake_1_1_records_1_1_metadata_1_1_i_metadatable.html',1,'Snowflake::Records::Metadata']]],
  ['imetadatacollection',['IMetadataCollection',['../interface_snowflake_1_1_records_1_1_metadata_1_1_i_metadata_collection.html',1,'Snowflake::Records::Metadata']]],
  ['imetadatalibrary',['IMetadataLibrary',['../interface_snowflake_1_1_records_1_1_metadata_1_1_i_metadata_library.html',1,'Snowflake::Records::Metadata']]],
  ['iniconfigurationserializer',['IniConfigurationSerializer',['../class_snowflake_1_1_configuration_1_1_ini_configuration_serializer.html',1,'Snowflake::Configuration']]],
  ['inputconfigurationsection',['InputConfigurationSection',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_configuration_section.html',1,'Snowflake::Configuration::Input']]],
  ['inputdevice',['InputDevice',['../class_snowflake_1_1_input_1_1_device_1_1_input_device.html',1,'Snowflake::Input::Device']]],
  ['inputenumerator',['InputEnumerator',['../class_snowflake_1_1_input_1_1_device_1_1_input_enumerator.html',1,'Snowflake::Input::Device']]],
  ['inputmapping',['InputMapping',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_mapping.html',1,'Snowflake::Configuration::Input']]],
  ['inputmappingconverter',['InputMappingConverter',['../class_snowflake_1_1_json_converters_1_1_input_mapping_converter.html',1,'Snowflake::JsonConverters']]],
  ['inputoption',['InputOption',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_option.html',1,'Snowflake::Configuration::Input']]],
  ['inputoptionattribute',['InputOptionAttribute',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_option_attribute.html',1,'Snowflake::Configuration::Input']]],
  ['inputserializer',['InputSerializer',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_serializer.html',1,'Snowflake::Configuration::Input']]],
  ['inputtemplate',['InputTemplate',['../class_snowflake_1_1_configuration_1_1_input_1_1_input_template.html',1,'Snowflake::Configuration::Input']]],
  ['inputtemplateattribute',['InputTemplateAttribute',['../class_snowflake_1_1_configuration_1_1_attributes_1_1_input_template_attribute.html',1,'Snowflake::Configuration::Attributes']]],
  ['iplatforminfo',['IPlatformInfo',['../interface_snowflake_1_1_platform_1_1_i_platform_info.html',1,'Snowflake::Platform']]],
  ['iplugin',['IPlugin',['../interface_snowflake_1_1_extensibility_1_1_i_plugin.html',1,'Snowflake::Extensibility']]],
  ['ipluginconfigoption',['IPluginConfigOption',['../interface_snowflake_1_1_extensibility_1_1_configuration_1_1_i_plugin_config_option.html',1,'Snowflake::Extensibility::Configuration']]],
  ['ipluginconfiguration',['IPluginConfiguration',['../interface_snowflake_1_1_extensibility_1_1_configuration_1_1_i_plugin_configuration.html',1,'Snowflake::Extensibility::Configuration']]],
  ['iplugincontainer',['IPluginContainer',['../interface_snowflake_1_1_extensibility_1_1_i_plugin_container.html',1,'Snowflake::Extensibility']]],
  ['ipluginmanager',['IPluginManager',['../interface_snowflake_1_1_services_1_1_i_plugin_manager.html',1,'Snowflake::Services']]],
  ['ipluginproperties',['IPluginProperties',['../interface_snowflake_1_1_extensibility_1_1_i_plugin_properties.html',1,'Snowflake::Extensibility']]],
  ['ipluginselectoption',['IPluginSelectOption',['../interface_snowflake_1_1_extensibility_1_1_configuration_1_1_i_plugin_select_option.html',1,'Snowflake::Extensibility::Configuration']]],
  ['iqueryprovider',['IQueryProvider',['../interface_snowflake_1_1_scraper_1_1_providers_1_1_i_query_provider.html',1,'Snowflake::Scraper::Providers']]],
  ['iqueryprovider_3c_20t_20_3e',['IQueryProvider&lt; T &gt;',['../interface_snowflake_1_1_scraper_1_1_providers_1_1_i_query_provider.html',1,'Snowflake::Scraper::Providers']]],
  ['iqueryprovidersource',['IQueryProviderSource',['../interface_snowflake_1_1_scraper_1_1_providers_1_1_i_query_provider_source.html',1,'Snowflake::Scraper::Providers']]],
  ['irecord',['IRecord',['../interface_snowflake_1_1_records_1_1_i_record.html',1,'Snowflake::Records']]],
  ['irecordlibrary',['IRecordLibrary',['../interface_snowflake_1_1_records_1_1_i_record_library.html',1,'Snowflake::Records']]],
  ['irecordlibrary_3c_20ifilerecord_20_3e',['IRecordLibrary&lt; IFileRecord &gt;',['../interface_snowflake_1_1_records_1_1_i_record_library.html',1,'Snowflake::Records']]],
  ['irecordlibrary_3c_20igamerecord_20_3e',['IRecordLibrary&lt; IGameRecord &gt;',['../interface_snowflake_1_1_records_1_1_i_record_library.html',1,'Snowflake::Records']]],
  ['irecordmetadata',['IRecordMetadata',['../interface_snowflake_1_1_records_1_1_metadata_1_1_i_record_metadata.html',1,'Snowflake::Records::Metadata']]],
  ['iromfileinfo',['IRomFileInfo',['../interface_snowflake_1_1_romfile_1_1_i_rom_file_info.html',1,'Snowflake::Romfile']]],
  ['irominfo',['IRomInfo',['../interface_snowflake_1_1_scraper_1_1_shiragame_1_1_i_rom_info.html',1,'Snowflake::Scraper::Shiragame']]],
  ['isavemanager',['ISaveManager',['../interface_snowflake_1_1_emulator_1_1_i_save_manager.html',1,'Snowflake::Emulator']]],
  ['iscrapedmetadatacollection',['IScrapedMetadataCollection',['../interface_snowflake_1_1_scraper_1_1_providers_1_1_i_scraped_metadata_collection.html',1,'Snowflake::Scraper::Providers']]],
  ['iscrapeengine',['IScrapeEngine',['../interface_snowflake_1_1_scraper_1_1_i_scrape_engine.html',1,'Snowflake::Scraper']]],
  ['iserialinfo',['ISerialInfo',['../interface_snowflake_1_1_scraper_1_1_shiragame_1_1_i_serial_info.html',1,'Snowflake::Scraper::Shiragame']]],
  ['ishiragameprovider',['IShiragameProvider',['../interface_snowflake_1_1_scraper_1_1_shiragame_1_1_i_shiragame_provider.html',1,'Snowflake::Scraper::Shiragame']]],
  ['isimplekeyvaluestore',['ISimpleKeyValueStore',['../interface_snowflake_1_1_utility_1_1_i_simple_key_value_store.html',1,'Snowflake::Utility']]],
  ['istoneprovider',['IStoneProvider',['../interface_snowflake_1_1_services_1_1_i_stone_provider.html',1,'Snowflake::Services']]],
  ['istructuredfilename',['IStructuredFilename',['../interface_snowflake_1_1_romfile_1_1_i_structured_filename.html',1,'Snowflake::Romfile']]],
  ['iuserinterface',['IUserInterface',['../interface_snowflake_1_1_services_1_1_i_user_interface.html',1,'Snowflake::Services']]]
];
